const data = [
  {
    primeiraColuna: "05/08/2022",
    qtd: 6,
    vlr: 132.01,
    txInter: 10.01,
    vlr1: 33.33,
    vlr2: 33.33,
    vlr3: 33.33,
    children: [
      {
        primeiraColuna: "Coop. 1",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 1",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
      {
        primeiraColuna: "Coop. 2",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 2",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    primeiraColuna: "06/08/2022",
    qtd: 6,
    vlr: 100.01,
    txInter: 10.01,
    vlr1: 33.33,
    vlr2: 33.33,
    vlr3: 33.33,
    children: [
      {
        primeiraColuna: "Coop. 1",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 1",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
      {
        primeiraColuna: "Coop. 1",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 1",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    primeiraColuna: "07/08/2022",
    qtd: 6,
    vlr: 100.01,
    txInter: 10.01,
    vlr1: 33.33,
    vlr2: 33.33,
    vlr3: 33.33,
    children: [
      {
        primeiraColuna: "Coop. 1",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 1",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
      {
        primeiraColuna: "Coop. 1",
        qtd: 3,
        vlr: 33.33,
        txInter: 3.33,
        vlr1: 3.33,
        vlr2: 3.33,
        vlr3: 3.33,
        children: [
          {
            primeiraColuna: "Agencia 1",
            qtd: 2,
            vlr: 3,
            txInter: 10,
            vlr1: 10,
            vlr2: 10,
            vlr3: 0,
            children: [
              {
                primeiraColuna: "Compra",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Saque",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
              {
                primeiraColuna: "Pagamento",
                qtd: 2,
                vlr: 3,
                txInter: 10,
                vlr1: 10,
                vlr2: 10,
                vlr3: 0,
              },
            ],
          },
        ],
      },
    ],
  },
];

const columns = [
  { title: "Data", key: "primeiraColuna" },
  { title: "Quantidade", key: "qtd" },
  { title: "Valor", key: "vlr" },
  { title: "Tx.Intercâmbio", key: "txInter" },
  { title: "Valor", key: "vlr1" },
  { title: "Valor", key: "vlr2" },
  { title: "Valor", key: "vlr3" },
];

export default {
  data,
  columns,
};
